### PR TITLE
2.0.14: deprecate getch, unify with new version of blessed.

### PR DESCRIPTION
**Pull request by jquast**
- simplify setup.py, no need for this weird stuff these days #280 
- update blessed #278
- prevent session continue after UnpicklingError #277
- deprecate getch #193

### CODE REVIEW

**Comment by haliphax** [comment]
Huzzah!

**Comment by jquast** [comment]
i forgot all about this, I've been running this on 1984.ws for months, probably fine to merge and release soon.

**Comment by jquast** [comment]
issue #285 could be a regression

**Comment by jquast** [comment]
For release sometime soon.

**Pull request merged**
