### PR TITLE
Deletion of the default/extras folder. External scripts can now be found here: https://github.com/x84-extras/x84-extras

### PR DESCRIPTION
**Pull request by ericolito**
deleted:    x84/default/extras/art/automsg.ans
	deleted:    x84/default/extras/automsg.py
	deleted:    x84/default/extras/bulletins.py
	deleted:    x84/default/extras/debug.py
	deleted:    x84/default/extras/hackernews.py
	deleted:    x84/default/extras/lightbar_main.py
	deleted:    x84/default/extras/productive.py
	deleted:    x84/default/extras/test_keyboard_keys.py
	deleted:    x84/default/extras/textbrowse.py

### CODE REVIEW

**Comment by megagumbo** [comment]
ok so how do i setup my dev environment to also include the new extras repo?

**Comment by ericolito** [comment]
ghost: just pull down the latest updates from the x84-extras repo and copy the script files that you want to use into your setup.

**Comment by haliphax** [comment]
You could also use git submodules to keep up to date with the extras. At this point, however, there aren't any.

**Comment by haliphax** [comment]
Moved to https://github.com/x84-extras/x84-extras

**Comment by jquast** [comment]
remember to make a branch next time

**Pull request merged**
