### PR TITLE
Update Session.py to remove extra args #230

### PR DESCRIPTION
**Pull request by crb02005**
Partially resolves issue with calling script with extra arguments.

### CODE REVIEW

**Comment by jquast** [comment]
Do I understand the intent correctly?

> To allow a main() function receiving no arguments to be called with arguments (arguments will be discarded)

If this is the case, why can't you just write a function like:
```python
def main(*args, **kwargs):
    ("and ignore the the value of args, kwargs")
```
?

**Comment by crb02005** [comment]
If you own all the scripts this function calls, they can be modified to
support that. Is this ever going to call an external script?

**Comment by jquast** [comment]
I don't follow, maybe you can provide a more precise use-case? Maybe we're not attacking the real problem here.


```python
def function():
    return 1

function(33, 99, some_keyword=101)
```

Why would you believe the above code should execute ?? It should absolutely fail. You've provided arguments that you certainly thought were expected and required.

"Explicit is better than Implicit"

I can't accept this:

- causes "the intended arguments passed to a script are thrown away in *some* circumstances", which is certain to cause at least one person a great deal of confusion.
- and very undocumented, not even a log statement, its an error, really. Somebody gosub()'d or goto()'d a script, sent arguments they expected were required by such script, and yet for some reason the author of that script decided they didn't want any, so they are discarded.  Yet you wouldn't even know.
- If there were a log statement, it would read: "HACKME: main() function has no argument signature, yet arguments *args, **kwargs were passed.  They have been DISCARDED". and it would be log level error, or even critical.
- It should raise an exception, that's what it does not, so I really need to understand why you would think otherwise. I need a concrete use case.

**Comment by crb02005** [comment]
You are absolute right.

**Pull request closed without merging**
